name: dockerhub-publish
on: push

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: login
      env:
        DOCKER_USER: ${{ secrets.docker_user }}
        DOCKER_TOKEN: ${{ secrets.docker_token }}
      run: |
        echo "login to docker"
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
    - name: build
      run: |
        echo "building docker images"
        make build
