name: dockerhub-publish
on: push

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: login
      env:
        USER: ${{ secrets.docker_user }}
        TOKEN: ${{ secrets.docker_token }}
      run: |
        echo "login to docker"
        docker login -u '$USER' -p '$TOKEN'
    - name: build
      run: |
        echo "building docker images"
        make build
