name: dockerhub-publish
on: push

jobs:
  images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.images-list.outputs.matrix }}
    steps:
    - id: images-list
      run: echo "::set-output name=matrix::{\"images\": $(ls -d */ | cut -d/ -f1 | jq -R -s 'split("\n")[:-1]')}"
  test:
    needs: images
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.images.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.images }}
